### PR TITLE
bug(jitterbug): fix dashboard scroll jitter, add safe area views to a…

### LINKED ISSUE #68: Fix dashboard screen jitter
## Expected Behavior

Dashboard screen should stay still unless the user is scrolling.

## Actual/Current Behavior

On scroll, the screen jitters back and forth vertically.

## Steps to Reproduce the Problem

  1. Add new folders with links
  2. Attempt to scroll on dashboard to view folders towards the bottom

### PR DESCRIPTION
**Pull request by dannysanchez559**
## Changes
_List Changes Introduced by this PR_
1. Added <SafeAreaViews> to all screens
2. Styled Modal background colors to match app design

## Purpose
To fix jitter animation on dashboard. The screen would jitter once user attempted scrolling. 

Closes #68

### CODE REVIEW

File: components/folder/EditFolderPage/EditFolderPage.js [hunk 1]
```diff
@@ -231,71 +231,73 @@ function EditFolderPage({ navigation, route }) {
...
+                placeholderTextColor="#c1c1c1"
+                onChangeText={setFolderName}
+                value={folderName}
+              />
+            </FolderInputSection>
+
+            <DescriptionSection>
+              <DescriptionLabel>Description</DescriptionLabel>
+              <DescriptionInput
+                // placeholder={route.params.folder.description}
```
Comment (Lap343) [inline components/folder/EditFolderPage/EditFolderPage.js:257]: still need this?

**Review by Lap343 — APPROVED** [review]

**Review by JayDampitan — APPROVED** [review]

File: components/folder/EditFolderPage/EditFolderPage.js (hunk 1 above)
Comment (dannysanchez559) [reply components/folder/EditFolderPage/EditFolderPage.js:257]: Yes i think paul got something planned with that. thanks!
